<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  
  <PropertyGroup>
    <PackageId>JohnOtt.LocalAiLibrary</PackageId>
    <Version>1.0.0</Version>
    <Authors>John Ott</Authors>
    <Description>AI Library used to support a local AI model.</Description>
    <RepositoryUrl>https://github.com/JohnOtt1962/Utilities</RepositoryUrl>
    <PackageReadmeFile>docs\README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
  
  <ItemGroup>
    <None Include="docs\README.md" Pack="true" PackagePath="docs\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="AiLibrary\AiEmail.cs" />
    <Compile Remove="AiLibrary\AITools\AITool.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="JohnOtt.Utilities" Version="1.0.0" />
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.11" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Extensions" Version="2.3.11" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.10" />
    <PackageReference Include="MimeKit" Version="4.17.0" />
  </ItemGroup>

</Project>
